add compute_min_max to AttrRangeFacetFilter
anti-social/elasticmagic-qf-attrs pull request #2
Opened 2021-12-02 08:14 UTC by efremov-dma

2021-12-07 15:32 UTC, anti-social requested changes

2021-12-07 15:32 UTC, anti-social commented on elasticmagic_qf_attrs/facet.py
> +    double float_val = Float.intBitsToFloat((int) v);
Can be `float` instead of `double`

2021-12-07 15:32 UTC, anti-social commented on elasticmagic_qf_attrs/facet.py
> +        state[attr_id] = new HashMap();
We can use array with 2 elements:
```
float[] min_max = state.get(attr_id);
if (min_max == null) {
    state[attr_id] = new float[] {float_val, float_val};
    continue;
}
```

2021-12-07 15:32 UTC, anti-social commented on elasticmagic_qf_attrs/facet.py
> +            )
Elasticsearch 7.x requires `combine_script` parameter

2021-12-13 12:01 UTC, efremov-dma commented on elasticmagic_qf_attrs/facet.py
> +for (v in doc[params.field].values) {
fixed

2021-12-13 12:01 UTC, efremov-dma commented on elasticmagic_qf_attrs/facet.py
> +    double float_val = Float.intBitsToFloat((int) v);
fixed

2021-12-13 12:01 UTC, efremov-dma commented on elasticmagic_qf_attrs/facet.py
> +        state[attr_id] = new HashMap();
fixed

2021-12-13 12:01 UTC, efremov-dma commented on elasticmagic_qf_attrs/facet.py
> +            reduced[attr_id] = new HashMap();
fixed

2021-12-13 12:01 UTC, efremov-dma commented on elasticmagic_qf_attrs/facet.py
> +            )
fixed

2021-12-14 11:24 UTC, merged